### ISSUE TITLE
Workmanager

### ISSUE THREAD

**Issue by karntrehan** [karntrehan/Android-IO18#6]
Add information about the work manager, comparison to other solutions, links, samples, etc.

**Comment by kevalpatel2106** [comment]
@karntrehan I wrote two blogs explaining work manager in detail. I think that will give a pretty good idea about the work manager to new developers. Do you want to add those links?

**Comment by karntrehan** [comment]
I have an eye on that. The plan is to write a description for the work manager and add article links + samples at the end. One of the articles is going to be yours for sure. 

If you want you can add the description too.
